name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      
    steps:
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: |
            ghcr.io/izer-xyz/gitea-pages:test

      -
        name: Validate Caddyfile
        run: |
          docker run --rm ghcr.io/izer-xyz/gitea-pages:test caddy validate -c /etc/caddy/Caddyfile
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: eslint
          git-user-name: Github Action - Publish
          skip-on-empty: "false"
          version-file: "package.yml"
          output-file: "false"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/izer-xyz/gitea-pages:${{ steps.changelog.outputs.tag }}
            ghcr.io/izer-xyz/gitea-pages:latest
      - 
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: |
            `docker pull ghcr.io/izer-xyz/gitea-pages:${{ steps.changelog.outputs.tag }}`

            ${{ steps.changelog.outputs.clean_changelog }}
            
            Or download from : 
             * https://github.com/izer-xyz/gitea-pages/pkgs/container/gitea-pages
            


